yarnPath: .yarn/releases/yarn-4.14.1.cjs
nodeLinker: node-modules
packageExtensions:
  "@opentui/core@*":
    peerDependenciesMeta:
      web-tree-sitter:
        optional: true
  "@opentui/react@*":
    peerDependenciesMeta:
      react-devtools-core:
        optional: true
      ws:
        optional: true
  "bun-ffi-structs@*":
    peerDependenciesMeta:
      typescript:
        optional: true
