import { Schema } from "effect";
import { HttpApiEndpoint, HttpApiGroup } from "effect/unstable/httpapi";

const NonEmptyString = Schema.String.pipe(Schema.check(Schema.isMinLength(1)));
const IdFromString = Schema.NumberFromString.pipe(Schema.check(Schema.isInt()));
const NullableString = Schema.NullishOr(Schema.String);
const NullableNumber = Schema.NullishOr(Schema.Number);
const NullableBoolean = Schema.NullishOr(Schema.Boolean);
const JsonArray = Schema.Array(Schema.Json);
const CourseRequestParams = {
  courseId: NonEmptyString,
};
const CourseRequestQuery = {
  id: NonEmptyString,
  zzud: NonEmptyString,
};
const Category = Schema.Struct({
  root_id: Schema.optionalKey(Schema.Int),
  name: Schema.optionalKey(Schema.String),
  category_id: Schema.Int,
  category_name: Schema.String,
  position: Schema.optionalKey(Schema.Int),
  category_type: Schema.optionalKey(Schema.String),
  second_category_url: Schema.optionalKey(Schema.String),
  third_category: Schema.optionalKey(JsonArray),
});
const Homework = Schema.Struct({
  is_archive: Schema.optionalKey(Schema.Boolean),
  related_poll: Schema.optionalKey(Schema.Boolean),
  is_shixun: Schema.Boolean,
  homework_id: Schema.Int,
  can_view_details: Schema.optionalKey(Schema.Boolean),
  name: Schema.String,
  private_icon: Schema.optionalKey(Schema.Boolean),
  status: Schema.Array(Schema.String),
  status_time: Schema.String,
  time_status: Schema.Int,
  allow_late: Schema.Boolean,
  author: Schema.String,
  author_img: Schema.optionalKey(Schema.String),
  author_login: Schema.optionalKey(Schema.String),
  created_at: Schema.String,
  unified_setting: Schema.Boolean,
  upper_category_name: Schema.optionalKey(NullableString),
  position: Schema.optionalKey(Schema.Int),
  publish_immediately: Schema.optionalKey(Schema.Boolean),
  end_immediately: Schema.optionalKey(Schema.Boolean),
  open_evaluate: Schema.optionalKey(NullableBoolean),
  lab_status: Schema.optionalKey(Schema.String),
  work_id: Schema.optionalKey(Schema.Int),
  work_status: Schema.optionalKey(Schema.Array(Schema.String)),
  un_commit_work: Schema.optionalKey(Schema.Boolean),
  shixun_identifier: Schema.optionalKey(Schema.String),
  shixun_status: Schema.optionalKey(Schema.Int),
  shixun_name: Schema.optionalKey(Schema.String),
  schools: Schema.optionalKey(JsonArray),
  opening_time: Schema.optionalKey(NullableString),
  is_enter_shixun: Schema.optionalKey(Schema.Boolean),
  shixun_enter_status: Schema.optionalKey(Schema.Int),
  shixun_marks: Schema.optionalKey(JsonArray),
  redo: Schema.optionalKey(Schema.Boolean),
  task_operation: Schema.optionalKey(JsonArray),
  shixun_finished_status: Schema.optionalKey(Schema.Int),
  student_passed_time: Schema.optionalKey(Schema.String),
  is_jupyter: Schema.optionalKey(Schema.Boolean),
  is_jupyter_lab: Schema.optionalKey(Schema.Boolean),
  myshixun_identifier: Schema.optionalKey(NullableString),
  publish_time: Schema.String,
  end_time: Schema.String,
  late_time: Schema.String,
  end_time_s: Schema.String,
  challenge_count: Schema.optionalKey(Schema.Int),
  checked_challenge_count: Schema.optionalKey(Schema.Int),
  finished_challenge_count: Schema.optionalKey(Schema.Int),
  student_work_id: Schema.Int,
});
const HomeworkCommonsResponse = Schema.Struct({
  course_identity: Schema.Int,
  homework_type: Schema.Int,
  course_public: Schema.Boolean,
  is_end: Schema.Boolean,
  main_category_id: Schema.Int,
  main_category_name: Schema.String,
  category_id: Schema.NullishOr(Schema.Int),
  category_name: NullableString,
  homeworks: Schema.Array(Homework),
  all_count: Schema.Int,
  published_count: Schema.Int,
  unpublished_count: Schema.Int,
  task_count: Schema.Int,
  query_total_count: Schema.Int,
  archive_count: Schema.Int,
  challenge_count: Schema.Int,
  finished_challenge_count: Schema.Int,
  finished_task_count: Schema.Int,
  min_finished_game: NullableNumber,
  shixun_total_count: Schema.Int,
});
const ExerciseSummary = Schema.Struct({
  id: Schema.Int,
  exercise_name: Schema.String,
  created_at: Schema.String,
  last_times: Schema.Int,
  screen_open: Schema.Boolean,
  screen_num: Schema.Int,
  is_locked: Schema.Boolean,
  is_random: Schema.Boolean,
  ip_limit: Schema.String,
  ip_bind: Schema.Boolean,
  answered_open: Schema.Boolean,
  identity_verify: Schema.Boolean,
  is_make_up_exercise: Schema.Boolean,
  open_phone_video_recording: Schema.Boolean,
  exercise_type: Schema.Int,
  simulate_exercise_num: Schema.Int,
  ai_push_wrong_question: Schema.Boolean,
  is_encrypt: Schema.Boolean,
  current_user_created: Schema.Boolean,
  show_setting_tips: Schema.Boolean,
  is_normal: Schema.Boolean,
  exercise_tips: Schema.Array(Schema.String),
  current_status: Schema.Int,
  exercise_left_time: NullableNumber,
  time: Schema.Int,
  whole_exercise_status: Schema.Int,
  exercise_status: Schema.Int,
  exercise_user_id: Schema.Int,
  screen_total_num: Schema.Int,
  screen_used_num: Schema.Int,
  user_simulate_num: Schema.Int,
  commit_method: Schema.String,
  author: Schema.String,
  is_redo: Schema.Int,
  before_start: Schema.String,
  off_limits: Schema.Boolean,
  open_appraise: Schema.Boolean,
});

export const Course = HttpApiGroup.make("Course")
  .add(
    HttpApiEndpoint.get("list", "/api/users/:username/courses.json", {
      params: {
        username: NonEmptyString,
      },
      query: {
        category: Schema.NullishOr(Schema.String),
        status: Schema.NullishOr(Schema.Literals(["processing", "end"])), // omitted = all
        page: Schema.Int.pipe(Schema.check(Schema.isGreaterThanOrEqualTo(1))),
        per_page: Schema.Int.pipe(Schema.check(Schema.isGreaterThanOrEqualTo(1))),
        sort_by: Schema.Literals(["updated_at", "created_at", "name"]),
        sort_direction: Schema.Literals(["desc", "asc"]),
        username: NonEmptyString,
        zzud: NonEmptyString,
      },
      success: Schema.Struct({
        count: Schema.Int.pipe(Schema.check(Schema.isGreaterThanOrEqualTo(0))),
        courses: Schema.Array(
          Schema.Struct({
            id: Schema.Int,
            name: Schema.String,
            members_count: Schema.Int,
            homework_commons_count: Schema.Int,
            attachments_count: Schema.Int,
            visits: Schema.Int,
            school: Schema.String,
            teacher_users: Schema.Array(Schema.String),
            created_at: Schema.String,
            is_end: Schema.Boolean,
            subject_id: Schema.NullishOr(Schema.String),
            subject_identifier: Schema.NullishOr(Schema.String),
            first_category_url: Schema.String,
            first_category: Schema.Struct({
              module_type: Schema.String,
              id: Schema.Int,
            }),
            is_public: Schema.BooleanFromBit,
            can_visited: Schema.Boolean,
            teacher: Schema.Struct({
              id: Schema.Int,
              real_name: Schema.String,
              avatar_url: Schema.String,
              school_name: Schema.String,
            }),
            forbid_visit_info: Schema.Struct({
              forbid_student_visit: Schema.Boolean,
              username: Schema.String,
            }),
          }),
        ),
      }),
    }),
  )
  .add(
    HttpApiEndpoint.get("topBanner", "/api/courses/:courseId/top_banner.json", {
      params: CourseRequestParams,
      query: CourseRequestQuery,
      success: Schema.Struct({
        copy_completed: Schema.Boolean,
        is_natural_language_data: Schema.Boolean,
        name: Schema.String,
        teacher_name: Schema.String,
        allow_view_message: Schema.Boolean,
        allow_apply_teacher: Schema.Boolean,
        copy_teacher_name: Schema.String,
        teacher_login: Schema.String,
        teacher_img: Schema.String,
        teacher_school: Schema.String,
        is_public: Schema.Boolean,
        student_join_approve: Schema.Boolean,
        student_join_pro: Schema.Boolean,
        show_unstart_exercise: Schema.Boolean,
        forbid_end_exercise: Schema.Boolean,
        switch_to_student: Schema.Boolean,
        switch_to_teacher: Schema.Boolean,
        switch_to_assistant: Schema.Boolean,
        teacher_users: Schema.Array(Schema.String),
        group_name: Schema.String,
        teacher_count: Schema.Int,
        student_count: Schema.Int,
        course_group_count: Schema.Int,
        credit: Schema.Number,
        course_id: Schema.Int,
        sub_discipline_id: NullableNumber,
        discipline_id: NullableNumber,
        class_period: Schema.Int,
        course_end: Schema.Boolean,
        start_date: NullableString,
        deadline: NullableString,
        code_halt: Schema.Boolean,
        show_invite_code: Schema.Boolean,
        invite_code: Schema.String,
        invite_code_halt: Schema.Int,
        visits: Schema.Int,
        course_identity: Schema.Int,
        excellent: Schema.Boolean,
        subject_identifier: Schema.String,
        third_party_name: NullableString,
        third_party_tip: Schema.Boolean,
        third_part_login_url: Schema.String,
        need_third_part_logined: Schema.Boolean,
        mooc_user_id: NullableNumber,
        mooc_course_id: NullableNumber,
        featured: Schema.Boolean,
        is_import_student: Schema.Boolean,
      }),
    }),
  )
  .add(
    HttpApiEndpoint.get("leftBanner", "/api/courses/:courseId/left_banner.json", {
      params: CourseRequestParams,
      query: CourseRequestQuery,
      success: Schema.Struct({
        is_teacher: Schema.Boolean,
        course_modules: Schema.Array(
          Schema.Struct({
            id: Schema.Int,
            name: Schema.String,
            init_name: Schema.String,
            type: Schema.String,
            position: Schema.Int,
            main_id: Schema.Int,
            category_url: Schema.String,
            second_category: Schema.optionalKey(Schema.Array(Category)),
          }),
        ),
        hidden_modules: Schema.Array(Schema.Json),
      }),
    }),
  )
  .add(
    HttpApiEndpoint.get("homeworkCommons", "/api/courses/:courseId/homework_commons.json", {
      params: CourseRequestParams,
      query: {
        coursesId: Schema.NullishOr(NonEmptyString),
        id: NonEmptyString,
        limit: Schema.Int.pipe(Schema.check(Schema.isGreaterThanOrEqualTo(1))),
        type: Schema.Int,
        status: Schema.NullishOr(Schema.Int),
        category: Schema.NullishOr(IdFromString),
        page: Schema.NullishOr(Schema.Int.pipe(Schema.check(Schema.isGreaterThanOrEqualTo(1)))),
        order: Schema.NullishOr(Schema.Int),
        search: Schema.NullishOr(Schema.String),
        sort_by: Schema.NullishOr(Schema.Literals(["created_at", "updated_at", "name_pinyin"])),
        sort_direction: Schema.NullishOr(Schema.Literals(["asc", "desc"])),
        zzud: NonEmptyString,
      },
      success: HomeworkCommonsResponse,
    }),
  )
  .add(
    HttpApiEndpoint.get("exercises", "/api/v2/courses/:courseId/exercises.json", {
      params: CourseRequestParams,
      query: {
        coursesId: NonEmptyString,
        limit: Schema.Int.pipe(Schema.check(Schema.isGreaterThanOrEqualTo(1))),
        type: Schema.String,
        id: NonEmptyString,
        page: Schema.NullishOr(Schema.Int.pipe(Schema.check(Schema.isGreaterThanOrEqualTo(1)))),
        zzud: NonEmptyString,
      },
      success: Schema.Struct({
        status: Schema.Int,
        message: Schema.String,
        total_count: Schema.Int,
        exercises_counts: Schema.Struct({
          exercises_all_counts: Schema.Int,
        }),
        exercises: Schema.Array(ExerciseSummary),
      }),
    }),
  );
